config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'

  get  '/upload', to: 'customers#upload_choices'
  post '/upload', to: 'customers#upload'

  namespace 'api' do
    namespace 'v1' do
      resources :customers
    end
  end

  resources :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :mobile, uniqueness: true, presence: true, format: { with: /(010|011|012|015)(\d{8})/ }
  validates :name, presence: true
  validates :address, presence: true
  # localhost:3000/api/v1/customers API controller to send JSON data
  # update edit delete
end

app/controllers/api/v1/customers_controller.rb
module Api
  module V1
    class CustomersController < ApplicationController

      def index
        customers = Customer.paginate(page: params[:page], per_page: 2)

        render json: customers, meta: pagination_dict(customers)
      end

      def show
        @customer = Customer.find(params[:id])

        render json: { status: 'SUCCESS', message: 'Loaded customer', data: @customer }, status: :ok
      end

      private

      def customer_params
        params.require(:customer).permit(:name, :mobile, :address)
      end

      def pagination_dict(collection)
        {
          current_page: collection.current_page,
          next_page: collection.next_page,
          previous_page: collection.previous_page, # use collection.previous_page when using will_paginate
          total_pages: collection.total_pages,
          total_entries: collection.total_entries
        }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
# frozen_string_literal: false

# class CustomersController
class CustomersController < ApplicationController
  def index
    @customers = Customer.paginate(page: params[:page], per_page: 5)
  end

  def upload
    @file = params[:file].path
    UploadJob.perform_now(@file)
    flash[:notice] = "If any unique customers were found in the excel sheet provided, they've been added"
    redirect_to root_path
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      flash[:notice] = 'Successfully updated customer'
      redirect_to root_path
    else
      flash[:alert] = 'An error occured, please make sure of all fields!'
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    flash[:notice] = 'Successfully deleted customer' 
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<h1>Edit Article</h1>

<%= form_with model: @customer do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :mobile %><br>
    <%= form.text_field :mobile %><br>
  </div>
  <div>
    <%= form.label :address %><br>
    <%= form.text_field :address %><br>
  </div>
  <%= link_to "Delete", customer_path(@customer) , method: :delete, data: { confirm: "Are you sure you want to delete #{@customer.name}?" } %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/index.html.erb
<h1>All customers added until now can be seen below. </h1>

<h2> Add new customers </h2>
<%= link_to 'Go to upload',upload_path %>


<div class="color2">
<strong>
    <div class="row">
        <div class="col-4">
            Name
        </div>
        <div class="col-4">
            Mobile
        </div>
        <div class="col-4">
            Address
        </div>
    </div>
</strong>
</div>

<% counter = 1 %>
<% @customers.each do |c| %>
    <% counter = counter + 1 %>

    <% if counter % 2 == 0  %>
        <div class="color1">
            <div class="row">
                <div class="col-3">
                    <%=c.name %>
                </div>
                <div class="col-3">
                    <%=c.mobile %>
                </div>
                <div class="col-3">
                    <%=c.address %>
                </div>
                <div class="col-3">
                    <%= link_to "Edit", edit_customer_path(c) %>
                </div>
                
            </div>
        </div>

    <% else %>
        <div class="color2">
            <div class="row">
                <div class="col-3">
                    <%=c.name %>
                </div>
                <div class="col-3">
                    <%=c.mobile %>
                </div>
                <div class="col-3">
                    <%=c.address %>
                </div>
                <div class="col-3">
                    <%= link_to "Edit", edit_customer_path(c) %>
                </div>
            </div>
        </div>
    <% end %>
 <%end%>

 <%= will_paginate @customers, class: 'digg_pagination' %>

app/views/customers/upload_choices.html.erb
<h1> Upload </h1>
<h3>Notes for excel sheet:</h3>
<ul>
    <li>Column 1 in excel sheet: Name, Column 2: Mobile number, Column 3: Address</li>
    <li>Number format is without the starting 0 and it will be saved in database with the 0. So for example 010 is 10.</li>
    <li>As an example, the following phone number 010######## should be 10######## in the excel sheet.</li>
</ul>
<%= form_with do |form| %>
    <%= form.file_field :file , accept:"application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"%>
    <%= form.submit %>
<%end%> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
    </div>
<%end%>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
    </div>
<%end%>